### ISSUE TITLE
Improve dependency management

### ISSUE THREAD

**Issue by The0ldM0nk** [The0ldM0nk/demo-tmdb#3]
- align project dependencies
- cleanup/upgrade as necessary

**Comment by vish21** [comment]
@The0ldM0nk Can you elaborate what you mean by align project dependencies?

**Comment by The0ldM0nk** [comment]
@vish21 as you can see project dependencies in this project are using the Gradle Build system and previously were messy.
I've tried to straighten it out so that it is easier to manage any dependency and gradle script while being a lot cleaner is self-explanatory.
